//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("TimersDBModel", "FK_TimerSession_0_0", "Timer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PersistableMultiTimer.Timer), "TimerSession", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PersistableMultiTimer.TimerSession), true)]

#endregion

namespace PersistableMultiTimer
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TimersDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TimersDBEntities object using the connection string found in the 'TimersDBEntities' section of the application configuration file.
        /// </summary>
        public TimersDBEntities() : base("name=TimersDBEntities", "TimersDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TimersDBEntities object.
        /// </summary>
        public TimersDBEntities(string connectionString) : base(connectionString, "TimersDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TimersDBEntities object.
        /// </summary>
        public TimersDBEntities(EntityConnection connection) : base(connection, "TimersDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Timer> Timer
        {
            get
            {
                if ((_Timer == null))
                {
                    _Timer = base.CreateObjectSet<Timer>("Timer");
                }
                return _Timer;
            }
        }
        private ObjectSet<Timer> _Timer;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TimerSession> TimerSession
        {
            get
            {
                if ((_TimerSession == null))
                {
                    _TimerSession = base.CreateObjectSet<TimerSession>("TimerSession");
                }
                return _TimerSession;
            }
        }
        private ObjectSet<TimerSession> _TimerSession;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Timer EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTimer(Timer timer)
        {
            base.AddObject("Timer", timer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TimerSession EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTimerSession(TimerSession timerSession)
        {
            base.AddObject("TimerSession", timerSession);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TimersDBModel", Name="Timer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Timer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Timer object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Timer CreateTimer(global::System.Int64 id, global::System.String name)
        {
            Timer timer = new Timer();
            timer.Id = id;
            timer.Name = name;
            return timer;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TimersDBModel", "FK_TimerSession_0_0", "TimerSession")]
        public EntityCollection<TimerSession> TimerSession
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TimerSession>("TimersDBModel.FK_TimerSession_0_0", "TimerSession");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TimerSession>("TimersDBModel.FK_TimerSession_0_0", "TimerSession", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TimersDBModel", Name="TimerSession")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TimerSession : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TimerSession object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="startDate">Initial value of the StartDate property.</param>
        /// <param name="endDate">Initial value of the EndDate property.</param>
        /// <param name="totalSeconds">Initial value of the TotalSeconds property.</param>
        /// <param name="idTimer">Initial value of the IdTimer property.</param>
        public static TimerSession CreateTimerSession(global::System.Int64 id, global::System.DateTime startDate, global::System.DateTime endDate, global::System.Int64 totalSeconds, global::System.Int64 idTimer)
        {
            TimerSession timerSession = new TimerSession();
            timerSession.Id = id;
            timerSession.StartDate = startDate;
            timerSession.EndDate = endDate;
            timerSession.TotalSeconds = totalSeconds;
            timerSession.IdTimer = idTimer;
            return timerSession;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime StartDate
        {
            get
            {
                return _StartDate;
            }
            set
            {
                OnStartDateChanging(value);
                ReportPropertyChanging("StartDate");
                _StartDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartDate");
                OnStartDateChanged();
            }
        }
        private global::System.DateTime _StartDate;
        partial void OnStartDateChanging(global::System.DateTime value);
        partial void OnStartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EndDate
        {
            get
            {
                return _EndDate;
            }
            set
            {
                OnEndDateChanging(value);
                ReportPropertyChanging("EndDate");
                _EndDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndDate");
                OnEndDateChanged();
            }
        }
        private global::System.DateTime _EndDate;
        partial void OnEndDateChanging(global::System.DateTime value);
        partial void OnEndDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 TotalSeconds
        {
            get
            {
                return _TotalSeconds;
            }
            set
            {
                OnTotalSecondsChanging(value);
                ReportPropertyChanging("TotalSeconds");
                _TotalSeconds = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalSeconds");
                OnTotalSecondsChanged();
            }
        }
        private global::System.Int64 _TotalSeconds;
        partial void OnTotalSecondsChanging(global::System.Int64 value);
        partial void OnTotalSecondsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 IdTimer
        {
            get
            {
                return _IdTimer;
            }
            set
            {
                OnIdTimerChanging(value);
                ReportPropertyChanging("IdTimer");
                _IdTimer = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdTimer");
                OnIdTimerChanged();
            }
        }
        private global::System.Int64 _IdTimer;
        partial void OnIdTimerChanging(global::System.Int64 value);
        partial void OnIdTimerChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TimersDBModel", "FK_TimerSession_0_0", "Timer")]
        public Timer Timer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Timer>("TimersDBModel.FK_TimerSession_0_0", "Timer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Timer>("TimersDBModel.FK_TimerSession_0_0", "Timer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Timer> TimerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Timer>("TimersDBModel.FK_TimerSession_0_0", "Timer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Timer>("TimersDBModel.FK_TimerSession_0_0", "Timer", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
